### ISSUE TITLE
Error posting to Instagram: Incompatible aspect ratio.

### ISSUE THREAD

**Issue by masanwar89** [germanProgq/Shorts_To_Reels#1]
[youtube] Extracting URL: https://www.youtube.com/shorts/joGZTa9cSXA
[youtube] joGZTa9cSXA: Downloading webpage
[youtube] joGZTa9cSXA: Downloading ios player API JSON
[youtube] joGZTa9cSXA: Downloading player dee49cfa
[youtube] joGZTa9cSXA: Downloading m3u8 information
[info] joGZTa9cSXA: Downloading 1 format(s): 18
[download] Destination: videos\joGZTa9cSXA.mp4
[download] 100% of  874.24KiB in 00:00:01 at 739.22KiB/s
DEBUG post_to_instagram: Original video size: 360x360, aspect ratio: 1.0
Error posting to Instagram: Invalid video width.
[youtube] Extracting URL: https://www.youtube.com/shorts/tD30a4iR9eI
[youtube] tD30a4iR9eI: Downloading webpage
[youtube] tD30a4iR9eI: Downloading ios player API JSON
[youtube] tD30a4iR9eI: Downloading m3u8 information
[info] tD30a4iR9eI: Downloading 1 format(s): 22
[download] Destination: videos\tD30a4iR9eI.mp4
[download] 100% of    5.95MiB in 00:00:09 at 613.93KiB/s
DEBUG post_to_instagram: Original video size: 720x1280, aspect ratio: 0.5625
Error posting to Instagram: Incompatible aspect ratio.
[youtube] Extracting URL: https://www.youtube.com/shorts/m_XmGok23LQ
[youtube] m_XmGok23LQ: Downloading webpage
[youtube] m_XmGok23LQ: Downloading ios player API JSON
[youtube] m_XmGok23LQ: Downloading m3u8 information
[info] m_XmGok23LQ: Downloading 1 format(s): 22
[download] Destination: videos\m_XmGok23LQ.mp4
[download] 100% of    3.24MiB in 00:00:06 at 491.48KiB/s
DEBUG post_to_instagram: Original video size: 720x1280, aspect ratio: 0.5625
Error posting to Instagram: Incompatible aspect ratio.

**Comment by germanProgq** [comment]
Hi! The issue has been fixed.

**Comment by masanwar89** [comment]
[youtube] Extracting URL: https://www.youtube.com/shorts/M3jM4zya1BU
[youtube] M3jM4zya1BU: Downloading webpage
[youtube] M3jM4zya1BU: Downloading ios player API JSON
[youtube] M3jM4zya1BU: Downloading android player API JSON
[youtube] M3jM4zya1BU: Downloading m3u8 information
[info] M3jM4zya1BU: Downloading 1 format(s): 22
[download] Destination: videos\M3jM4zya1BU.mp4
[download] 100% of    7.76MiB in 00:00:05 at 1.31MiB/s
Error posting to Instagram: Duration is more than 15s.
[youtube] Extracting URL: https://www.youtube.com/shorts/FNMw-Cd0058
[youtube] FNMw-Cd0058: Downloading webpage
[youtube] FNMw-Cd0058: Downloading ios player API JSON
[youtube] FNMw-Cd0058: Downloading android player API JSON
[youtube] FNMw-Cd0058: Downloading m3u8 information
[info] FNMw-Cd0058: Downloading 1 format(s): 22
[download] Destination: videos\FNMw-Cd0058.mp4
[download] 100% of    1.65MiB in 00:00:01 at 971.39KiB/s
Error posting to Instagram: Duration is more than 15s.
[youtube] Extracting URL: https://www.youtube.com/shorts/Lq0G9_ioG7g
[youtube] Lq0G9_ioG7g: Downloading webpage
[youtube] Lq0G9_ioG7g: Downloading ios player API JSON
[youtube] Lq0G9_ioG7g: Downloading android player API JSON
[youtube] Lq0G9_ioG7g: Downloading m3u8 information
[info] Lq0G9_ioG7g: Downloading 1 format(s): 22
[download] Destination: videos\Lq0G9_ioG7g.mp4
[download] 100% of   10.52MiB in 00:00:07 at 1.39MiB/s
Error posting to Instagram: Duration is more than 15s.
[youtube] Extracting URL: https://www.youtube.com/shorts/I6K9iunFnP8
[youtube] I6K9iunFnP8: Downloading webpage
[youtube] I6K9iunFnP8: Downloading ios player API JSON
[youtube] I6K9iunFnP8: Downloading android player API JSON
[youtube] I6K9iunFnP8: Downloading m3u8 information
[info] I6K9iunFnP8: Downloading 1 format(s): 22
[download] Destination: videos\I6K9iunFnP8.mp4
[download] 100% of    7.58MiB in 00:00:05 at 1.38MiB/s
Error posting to Instagram: Duration is more than 15s.
[youtube] Extracting URL: https://www.youtube.com/shorts/whlR137meI8
[youtube] whlR137meI8: Downloading webpage
[youtube] whlR137meI8: Downloading ios player API JSON
[youtube] whlR137meI8: Downloading android player API JSON
[youtube] whlR137meI8: Downloading m3u8 information
[info] whlR137meI8: Downloading 1 format(s): 18
[download] videos\whlR137meI8.mp4 has already been downloaded
[download] 100% of  787.34KiB
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_private_api\client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Belajar Python\shorttoig\Shorts_To_Reels\main.py", line 128, in <module>
    main()
  File "D:\Software\Belajar Python\shorttoig\Shorts_To_Reels\main.py", line 120, in main
    post_to_instagram(api, output_path, caption)
  File "D:\Software\Belajar Python\shorttoig\Shorts_To_Reels\main.py", line 94, in post_to_instagram
    api.post_video(video_data, size=(width, height), duration=duration, thumbnail_data=thumbnail_data, caption=caption, to_reel=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_private_api\endpoints\upload.py", line 551, in post_video
    res = self._call_api(endpoint, params=params, unsigned=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_private_api\client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_private_api\errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found

**Comment by germanProgq** [comment]
Hi! Are you sure you entered the correct credentials for your instagram account?

**Comment by germanProgq** [comment]
Just added more debugging to the code, fixed a bit of an issue with an api. Check if it works now.
